### ISSUE TITLE
Problems running association tests

### ISSUE THREAD

**Issue by jpuritz** [rnowling/asaph#4]
Previous commands run:
`asaph_import --vcf-gz SNP.MASKED.noinbred.Chr5and6.vcf.gz --workdir ./asaph`
`asaph_dim_reduc --workdir ./asaph train --n-components 10 --model-type PCA`
`asaph_dim_reduc --workdir ./asaph/ explained-variance-analysis`

Command line that gives error:
`asaph_dim_reduc --workdir ./asaph/ snp-association-tests --components 1 2 3 `

Output:
```
/home/jpuritz/miniconda3/envs/asaph/lib/python3.7/site-packages/umap_learn-0.5.0rc1-py3.7.egg/umap/__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  warn("Tensorflow not installed; ParametricUMAP will be unavailable")
Traceback (most recent call last):
  File "/home/jpuritz/miniconda3/envs/asaph/bin/asaph_dim_reduc", line 4, in <module>
    __import__('pkg_resources').run_script('asaph==2.0', 'asaph_dim_reduc')
  File "/home/jpuritz/miniconda3/envs/asaph/lib/python3.7/site-packages/pkg_resources/__init__.py", line 665, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jpuritz/miniconda3/envs/asaph/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1463, in run_script
    exec(code, namespace, namespace)
  File "/home/jpuritz/miniconda3/envs/asaph/lib/python3.7/site-packages/asaph-2.0-py3.7.egg/EGG-INFO/scripts/asaph_dim_reduc", line 451, in <module>
    snp_linreg_association_tests(args)
  File "/home/jpuritz/miniconda3/envs/asaph/lib/python3.7/site-packages/asaph-2.0-py3.7.egg/EGG-INFO/scripts/asaph_dim_reduc", line 326, in snp_linreg_association_tests
    for i, pair in enumerate(data_model.snp_feature_map.iteritems()):
AttributeError: 'Features' object has no attribute 'snp_feature_map'
```

**Comment by jpuritz** [comment]
Really this is the first error.  I tried commenting out line 266 which led to the above error.

```
asaph_dim_reduc --workdir ./asaph/ snp-association-tests --components 1 2 3
/usr/local/lib/python3.7/site-packages/umap_learn-0.5.0rc1-py3.7.egg/umap/__init__.py:9: UserWarning: Tensorflow not installed; ParametricUMAP will be unavailable
  warn("Tensorflow not installed; ParametricUMAP will be unavailable")
/home/jpuritz/.local/lib/python3.7/site-packages/sklearn/base.py:334: UserWarning: Trying to unpickle estimator PCA from version 0.24.0rc1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "/usr/local/bin/asaph_dim_reduc", line 4, in <module>
    __import__('pkg_resources').run_script('asaph==2.0', 'asaph_dim_reduc')
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.7/site-packages/asaph-2.0-py3.7.egg/EGG-INFO/scripts/asaph_dim_reduc", line 453, in <module>
    snp_logreg_association_tests(args)
  File "/usr/local/lib/python3.7/site-packages/asaph-2.0-py3.7.egg/EGG-INFO/scripts/asaph_dim_reduc", line 266, in snp_logreg_association_tests
    fit_intercept=False)
  File "/home/jpuritz/.local/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'n_iter'
```

**Comment by jpuritz** [comment]
I've tried multiple python environments and scikit-learn versions.  They call give the same error.  I'm trying to detect inversions via PCA.

**Comment by rnowling** [comment]
Hi Jon,

Sorry about the issues.  I've been modifying the project to add some new features and accidentally merged some of those changes into the main branch.  Please try using this branch:

https://github.com/rnowling/asaph/tree/plos-one

You can find example commands in the PLOS One paper here:

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0240429

Please feel free to email me at nowling@msoe.edu, and I'd be happy to help further.
